# Generated by Django 2.1 on 2018-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('qualification', models.CharField(max_length=120)),
                ('website', models.URLField()),
                ('years_experience', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
