# Generated by Django 2.1 on 2018-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=200)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Expert'),
        ),
    ]
