# Generated by Django 2.1 on 2018-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180904_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='expert',
            old_name='role',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='expert',
            name='profession',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
