# Generated by Django 2.1 on 2018-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180904_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
